# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe7c0fe7f6a5727dd5eeac7674484292d4e838a0e2ec515f7e676c397cc0261956fa5e1d3410c7a3f65cd645b1d725cf3287f6dfd0bba0933042bf56ac16f6b6

test:
  secret_key_base: c6237bef00e01e97185d024004c775db0d2f66bba495db652f04159d8c9f4ddaf0ba0e09af7ae0b6d36197a8186cf899e3e90c05ff31a95c0d82418f44c24f4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
